extends:
  - './node_modules/@nlib/lint/.eslintrc.json'
env:
  node: true
  es6: true
overrides:
  -
    files:
      - '*.script.js'
    env:
      node: false
      es6: false
    globals:
      self: true
  -
    files:
      - 'test/**'
    rules:
      no-loop-func: 'off'
